### ISSUE TITLE
Special Character(s) in Passwords KILLS Application

### ISSUE THREAD

**Issue by mattyteds** [Moussa/TF2IdleGUI#11]
I happen to have a % in one of my passwords. If I try to add an account with that password the program stays on the add account screen and an error is thrown in the log (Which stores my password in plan text D: )

type = type 'exceptions.ValueError'
value = invalid interpolation syntax in 'Pass%Word' at position 4
tback = traceback object at 0x02D8F030
type = class 'ConfigParser.NoOptionError'
value = No option 'account_nickname' in section: 'Account-test'
tback = traceback object at 0x02D8B878

You have to delete the idle.ini to get the application to even open again. I don't know if any other special characters case this.

**Comment by Moussa** [comment]
This is fixed and will be pushed in the next release soon. Thanks for reporting it.
