### ISSUE TITLE
Easy Sandbox Mode and Secondary Steamapps folder

### ISSUE THREAD

**Issue by ghost** [Moussa/TF2IdleGUI#12]
It appears that Easy Sandbox mode is using the Secondary Steamapps folder to launch Steam.exe instead of the Steam installation location.  When I set the Secondary Steamapps folder to my steamapps folder then click Start Idling, it gives me an error that it cannot find Steam.exe in that folder.  However when I change the Secondary Steamapps folder to the same folder as my Steam installation, Steam launches correctly.

I think the issue might be this line, but I haven't investigated it a ton nor is Python a language I'm familiar with.
https://github.com/Moussekateer/TF2IdleGUI/blob/master/Sandboxie.py#L34

**Comment by Moussa** [comment]
Thanks for pointing this out, it is indeed an error! I will make it point to the primary steam installation instead
